packages:
  - "apps/*"
  - "packages/*"

pmOnFail: error

nodeVersion: 24.19.0
engineStrict: true

strictDepBuilds: true

allowBuilds:
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
