packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@types/node": ^22.15.3
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  clsx: ^2.1.1
  eslint: ^9.39.1
  globals: ^16.5.0
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: 5.9.2

catalogMode: prefer

pmOnFail: error

nodeVersion: 24.19.0
engineStrict: true

strictDepBuilds: true

allowBuilds:
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
