import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars = {
  docsSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
} satisfies SidebarsConfig;

export default sidebars;
